
model: QTT
dimensions: 2
exp_name: noise_exp_bs4096_color_new

use_wandb: 1
use_tqdm: 0
save_images_locally_wandb: 1

use_TTNF_sampling: 0
payload: 3
payload_position: first_core

num_iterations: 8192

# LR stuff 
lr: 0.01
lr_decay_factor: 0.9
lr_decay_factor_until_next_upsampling: 0.1
warmup_steps: 50
factor_reduce_lr_based_on_noise: 0.02

canonization: middle
compression_alg: compress_all

max_batch_size: 4096 # 64**2  

iterations_for_upsampling_arr: [[128,256,512,1024, 2048] ,[]]


# Tilting
tilt_angle_arr:
  - 0
tilting_mode: 0

# Noise
#noise_type_arr: [None, gaussian, laplace]
noise_type_arr: [None, gaussian, laplace]

noise_std_arr: [0, 0.05, 0.1, 0.2, 0.5, 1.0]
# Regularization
regularization_type: None
regularization_weight: 0.00

compute_reconstruction: 1
calculate_psnr_while_training: 0

seeds: [0, 1, 2]