exp_name: bs512_save_figs
model: QTT
dimensions: 3
use_wandb: 1
use_tqdm: 0
use_TTNF_sampling: 0
save_images_locally_wandb: 1
payload: 0
payload_position: grayscale
num_iterations: 10000
lr: 0.01
lr_decay_factor: 0.9
lr_decay_factor_until_next_upsampling: 0.1
warmup_steps: 50
canonization: middle
compression_alg: compress_all

max_batch_size: 262144 #512**2

iterations_for_upsampling_arr: [[16,48,144],[16,48,144,432],[16,48,144,432,1296],[16,48,144,432,1296,3888],[48,144,432,1296,3888,11664,34992],[]]
# iterations_for_upsampling_arr: [[]]
tilt_angle_arr: [0]
tilting_mode: 0
noise_type_arr: [None]
noise_std_arr: [0]
regularization_type: None
regularization_weight: 0.00
compute_reconstruction: 1
calculate_psnr_while_training: 0

seeds: [0,1,2]

save_learned_recon: 1