model: QTT
exp_name: upsampling
dimensions: 3
use_wandb: 1
use_tqdm: 0
save_images_locally_wandb: 1

use_TTNF_sampling: 0
payload: 0
payload_position: grayscale
num_iterations: 10000
lr: 0.01
lr_decay_factor: 0.9
lr_decay_factor_until_next_upsampling: 0.1
warmup_steps: 50
canonization: middle
compression_alg: compress_all
#max_batch_size: 16384
max_batch_size: 262144 #512**2
batch_size_arr: [65536] 
iterations_for_upsampling_arr: [[  64, 128, 256],[  128, 256], [  64, 128, 256, 512],[  128, 256, 512],[ 256, 512],[ 512], [], [ 32, 64, 128, 256, 512]]
# iterations_for_upsampling_arr: [[]]
tilt_angle_arr: [0]
tilting_mode: 0
noise_type_arr: [None]
noise_std_arr: [0]
regularization_type: None
regularization_weight: 0.00
compute_reconstruction: 1
calculate_psnr_while_training: 0

seeds: [0, 1, 2]