model: QTT
dimensions: 2
use_wandb: 1
use_tqdm: 0
save_images_locally_wandb: 1
use_TTNF_sampling: 0
payload: 0
payload_position: grayscale
num_iterations: 10000
lr: 0.01
lr_decay_factor: 0.9
lr_decay_factor_until_next_upsampling: 0.1
factor_reduce_lr_based_on_noise: 0.02
warmup_steps: 50
canonization: middle
compression_alg: compress_all

max_batch_size: 262144 #512**2

num_iterations_arr: [  4096, 8192]
batch_size_arr: [ 262144, 65536, 4096]
lr_arr: [ 0.005, 0.001, 0.0005, 0.0001]

subset_to_train_on_arr: [0.01, 0.05, 0.1, 0.2, 0.5, 1.0]
default_val_for_non_sampled: 0.0

iterations_for_upsampling_arr: [[32,96,288,864,2592],[]]

tilt_angle_arr: [0]
tilting_mode: 0
noise_type_arr: [None]
noise_std_arr: [0]
regularization_type: None
regularization_weight: 0.00
compute_reconstruction: 1
calculate_psnr_while_training: 0

seeds: [0, 1, 2]
