target: data/images/lena.png
base_config: configs/base_configs/2d_base_config_upsampling.yaml
exp_name: lena_sigma_core_init
model: QTT
end_reso: 512

lr_arr:
    - 0.01
    - 0.005
    - 0.02


init_reso_arr:
    - 32
    - 512
max_ranks_arr:
    - 100


sigma_init_arr:
    - 0.5
    - 0.1
    - 0.05
    - 0.01
    - 0.005
    - 0.001


num_iterations_arr: [ 1000, 3000]
batch_size_arr: [  4096, 16384, 65536]

iterations_for_upsampling_arr: [[64,128,256,512], []]