target: data/3d_data/downsampled_volumes_flower/flower_512.raw
base_config: configs/base_configs/3d_base_config.yaml

model: Tucker
end_reso: 512
num_iterations: 13824 # 3*3072



init_reso_arr:
    - 8
    - 512
max_ranks_arr:
    - 146
    - 117
    - 81

