target: data/3d_data/downsampled_volumes_flower/flower_1024.raw
base_config: configs/base_configs/3d_base_config.yaml

model: Tucker
end_reso: 1024
num_iterations: 69984
init_reso_arr:
    - 64
    - 1024
max_ranks_arr:
    - 138
    - 180
    - 124

