target: data/images/barbara256.png
base_config: configs/base_configs/2d_base_config_subset_sampling.yaml

model: QTT
end_reso: 256
seeds: [1]

rank_upsampling_rank_range : []
rank_upsampling_iteration_range : []

lr_arr: [ 0.001, 0.0001]
init_reso_arr:
    - 256
max_ranks_arr:
    - 16
    - 24
    - 32

regularization_weight_arr:
    - 0

regularization_type: "TV"



subset_to_train_on: 0.9
plot_subsampled_target: 0
is_random_box_impainting : 0

# regularization_type: "L1"

exp_name: barbara_subset_sampling
dimensions: 2
use_wandb: 1
use_tqdm: 0
save_images_locally_wandb: 1
use_TTNF_sampling: 0
payload: 3
payload_position: first_core

num_iterations: 2000
lr: 0.01
lr_decay_factor: 0.9
lr_decay_factor_until_next_upsampling: 0.1
warmup_steps: 50
canonization: middle
compression_alg: compress_all

#num_iterations_arr: [1024, 2048, 4096, 8192]
num_iterations_arr: [  100000, 16384, 32768, 65536, 100000]
batch_size_arr: [1]


subset_to_train_on_arr: [ 0.01]
default_val_for_non_sampled: 0.0
#factor_reduce_lr_based_on_noise: 0.02
factor_reduce_lr_based_on_noise: 0

iterations_for_upsampling_arr: [ []]
#iterations_for_upsampling_arr: [ [500, 1000, 2000, 4000],[500, 1000, 4000, 8000], [250, 1000, 2000, 4000], [1000, 2000, 8000, 16000]]
#iterations_for_upsampling_arr: [ [100, 200, 400, 800], [ 200, 400, 800],[ 200, 400], [ 100, 400, 400]]
tilt_angle_arr: [0]
tilting_mode: 0
noise_type_arr: [None]
noise_std_arr: [0]
compute_reconstruction: 1

calculate_psnr_while_training: 0


