target: data/images/lena.png
base_config: configs/base_configs/2d_base_config_subset_sampling.yaml

model: CP
end_reso: 512
seeds: [1]

lr_arr: [ 0.003, 0.01]
init_reso_arr:
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
max_ranks_arr:
    - 120
    - 100

regularization_weight_arr:
    - 0.1
    - 0.3
    - 0.5


subset_to_train_on: 0.9
plot_subsampled_target: 0
is_random_box_impainting : 1

regularization_type: "TV"
# regularization_type: "L1"

exp_name: blocks_box_subset_sampling
dimensions: 2
use_wandb: 1
use_tqdm: 0
save_images_locally_wandb: 1
use_TTNF_sampling: 0
payload: 3
payload_position: first_core

num_iterations: 2000
lr: 0.01
lr_decay_factor: 0.9
lr_decay_factor_until_next_upsampling: 0.1
warmup_steps: 50
canonization: middle
compression_alg: compress_all

num_iterations_arr: [ 1000,3000]
batch_size_arr: [  4096, 262144]


subset_to_train_on_arr: [ 0.90, 0.80]
default_val_for_non_sampled: 0.0
factor_reduce_lr_based_on_noise: 0.02

iterations_for_upsampling_arr: [[64,128,256,512],[64, 128,256], [256, 512], [512], []]
tilt_angle_arr: [0]
tilting_mode: 0
noise_type_arr: [None]
noise_std_arr: [0]
compute_reconstruction: 1
calculate_psnr_while_training: 0


