target: data/images/pluto_4k.png
base_config: configs/base_configs/2d_base_config_subset_sampling.yaml

model: QTT
end_reso: 4096

lr_arr: [ 0.005]

init_reso_arr:
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
max_ranks_arr:
    # - 200
    - 300

