target: data/images/tokyo_downsampled_images/tokyo_8k.png
base_config: configs/base_configs/2d_base_config.yaml

model: QTT
lr: 0.005
end_reso: 8192
num_iterations: 8192

init_reso_arr:
    - 128
    - 8192
max_ranks_arr:
    - 350
    - 250
    - 150



#use_TTNF_sampling: 0
#payload: 0
#payload_position: grayscale

use_TTNF_sampling: 1
payload: 1
payload_position: first_core
