target: data/images/girl_downsampled_images/girl_4k.png
base_config: configs/base_configs/2d_base_config_upsampling.yaml

model: CP
end_reso: 4096
num_iterations: 1536

init_reso_arr:
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
max_ranks_arr:
    - 180
    - 92


lr_arr: [ 0.01]

use_wandb: 1
use_tqdm: 0
wandb_limited_logging: 0
