target: data/images/marseille_4k.png
base_config: configs/base_configs/2d_base_config_noise.yaml

model: CP
end_reso: 4096


init_reso_arr:
    - 128
    - 4096
max_ranks_arr:
    # - 92
    - 180








