target: data/3d_data/downsampled_volumnes_isotropic/isotropic512.npy
base_config: configs/base_configs/3d_base_config.yaml

model: VM
end_reso: 512
num_iterations: 13824 # 3*3072

init_reso_arr:
    - 8
    - 512
max_ranks_arr:
    - 5
    - 4
    - 1



#use_TTNF_sampling: 0
#payload: 0
#payload_position: grayscale