target: data/3d_data/downsampled_volumes_flower/flower_512.raw
base_config: configs/base_configs/3d_base_config.yaml

model: QTT
lr: 0.008
end_reso: 512
num_iterations: 13824 # 3*3072

init_reso_arr:
    - 8
    - 512
max_ranks_arr:
    - 350
    - 250
    - 150



#use_TTNF_sampling: 0
#payload: 0
#payload_position: grayscale

use_TTNF_sampling: 1
payload: 1
payload_position: first_core
