target: data/3d_data/downsampled_volumes_flower/flower_64.raw
base_config: configs/base_configs/3d_base_config.yaml

model: QTT
lr: 0.008
end_reso: 64
num_iterations: 512

init_reso_arr:
    - 8
    - 64
max_ranks_arr:
    - 80
    - 40
    - 20





