target: data/images/girl_downsampled_images/girl_2k.png
base_config: configs/base_configs/2d_base_config.yaml

model: CP
end_reso: 2048
num_iterations: 2048


init_reso_arr:
    - 128
    - 2048
max_ranks_arr:
    - 28
    - 88
    - 228





