target: data/images/girl_downsampled_images/girl_16k.png
base_config: configs/base_configs/2d_base_config.yaml

model: CP
end_reso: 16384
num_iterations: 16384

init_reso_arr:
    - 128
    - 16384
max_ranks_arr:
    - 108
    - 67
    # - 37


