target: data/images/girl_downsampled_images/girl_1k.png
base_config: configs/base_configs/2d_base_config.yaml

model: CP
end_reso: 1024
num_iterations: 1024

init_reso_arr:
    - 128
    - 1024
max_ranks_arr:
    - 212
    - 70
    - 24
