target: data/images/girl_downsampled_images/girl_1k.png
base_config: configs/base_configs/2d_base_config_rank_upsampling.yaml

exp_name: rank_upsampling_images

model: QTT
end_reso: 1024
num_iterations: 2048
seeds: [0,1]

iterations_for_upsampling_arr: [[]]
init_reso_arr:
    - 1024
max_ranks_arr:
    - 200

lr_arr:
    - 0.008
    - 0.003

rank_upsampling_rank_range_arr:
    - []
    - [100, 200, 2]
    - [100, 200, 4]
    - [100, 200, 8]
    - [200, 200, 2]
    - [200, 200, 4]
    - [200, 200, 8]

rank_upsampling_iteration_range_arr:
    - []
    - [100, 1000]
    - [100, 1500]
    - [250, 1000]
    - [250, 1500]
    - [250, 750]
    - [100, 1000]
    