target: data/3d_data/downsampled_volumnes_isotropic/isotropic256.npy
base_config: configs/base_configs/3d_base_config_noise.yaml

model: CP
end_reso: 256


init_reso_arr:
    - 8
    - 256
max_ranks_arr:
    - 1070








