target: data/3d_data/downsampled_volumes_flower/flower_1024.raw
base_config: configs/base_configs/3d_base_config.yaml

model: CP
end_reso: 1024
num_iterations: 69984
#max_batch_size: 262144 #512**2 # 1014 too big


init_reso_arr:
    - 64
    - 1024
max_ranks_arr:
    - 2000
    - 1035
    - 755
