target: data/3d_data/downsampled_volumes_flower/flower_128.raw
base_config: configs/base_configs/3d_base_config.yaml

model: CP
end_reso: 128
num_iterations: 1536

init_reso_arr:
    - 8
    - 128
max_ranks_arr:
    - 540
    - 280
    - 120
